# Using NumPy

Let us use NumPy. 

Quant-econ <https://lectures.quantecon.org/py/numpy.html> provides a useful introduction to it.

A convention is to import it as "np".

In [2]:
import numpy as np

Perhaps the most important thing defined in NumPy is the _Numpy array_ (ndarray type).

NumPy arrays are very useful in numerical programming. We will use it to represent vectors and matrices.

In [3]:
a = np.array([1,2,3])
print(a)
type(a)

[1 2 3]


numpy.ndarray

Unlike a list, data must be homogenous. The (common) type of all elements in array a can be seen by looking at the _dtype_ attribute of a: 

In [4]:
a.dtype

dtype('int64')

As we did for a list, we can _slice_ a NumPy array:

In [5]:
a[:2]

array([1, 2])

In [6]:
a[1:]

array([2, 3])

We can see the dimension of a by looking at the _shape_ attribute of a:

In [7]:
a.shape

(3,)

This means that a is neither a column vector nor a row vector. It is called a _flat array_.

We can make it a column vector by assigning (3,1) to a.shape.

In [8]:
a.shape = (3,1)

Now a is a 3-by-1 vector.

In [ ]:
print(a)

Alternatively, we can make it a row vector by assigning (1,3) to a.shape.

In [ ]:
a.shape = (1,3)

Now a is a 1-by-3 vector.

In [ ]:
print(a)

We can create a NumPy array of Booleans

In [9]:
np.array([True,False,False])

array([ True, False, False])

and that of floating point numbers

In [10]:
d = np.array([1.0, 7.5, np.pi])
print(d)
print(d.dtype)

[1.         7.5        3.14159265]
float64


What happens if we apply _numpy.array_ to a list that contains mixed type elements?

In [11]:
d = np.array([True, 1.0, 'test'])
print(d)
print(d.dtype)


['True' '1.0' 'test']
<U32


In this case, all elements are converted to string. 

In [12]:
a = np.array([1,2,3])
b = np.array([5,4,3])

In [13]:
print(a+b)
print(a*b)
print(a/b)

[6 6 6]
[5 8 9]
[0.2 0.5 1. ]


In [14]:
C = np.array([[1, 3, 6],
         [3, 2, 2],
         [8, 9, 5]])
print(C)

[[1 3 6]
 [3 2 2]
 [8 9 5]]


In [15]:
a @ C

array([31, 34, 25])

In [16]:
a @ C @ b

366

## Array creation methods

See also <https://docs.scipy.org/doc/numpy/reference/routines.array-creation.html>.

In [17]:
# an array of zeros
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [18]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [19]:
# a 2-dimensional array with ones on the diagonal and zeros elsewhere
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [20]:
# an array with ones
np.ones((5,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [21]:
# an array filled with a specified value
np.full((4,3), True)

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [28]:
# an empty array (values not initialized)
np.empty((4,))

array([1., 1., 1., 1.])

In [29]:
# an equally spaced grid
np.linspace(1.0, 8.0, 5)

array([1.  , 2.75, 4.5 , 6.25, 8.  ])

## Making copies (or not)

Importantly, we cannot make a copy using an assignment statement. 

In [42]:
a = np.array([[1, 2], [3, 4]])

Suppose we want to make a copy of a, and to name it b. 

Then the following works perfectly in Matlab:

In [43]:
b = a # Does this make a copy of a?

In [44]:
print(b)

[[1 2]
 [3 4]]


So far, so good. If b is an independent copy of a, then we should be able to change it without affecting a.

In [45]:
b[0,0] = 10
print(b)

[[10  2]
 [ 3  4]]


What about a?

In [46]:
print(a)

[[10  2]
 [ 3  4]]


As <https://lectures.quantecon.org/py/numpy.html> puts it,

"What’s happened is that we have changed a by changing b

...

The name b is bound to a and becomes just another reference to the array

Hence, it has equal rights to make changes to that array"

To avoid this, we had better
1. Create a new (empty) vector and assign it to the name b. In Quant-Econ, numpy.empty_like() is used. Here we use an alternative.
2. Then use numpy.copyto() to copy a to b.

In [47]:
a = np.array([[1, 2], [3, 4]])

b = np.zeros(a.shape)
np.copyto(b, a) 

print(b)

[[1. 2.]
 [3. 4.]]


In [48]:
b[0,0] = 10
print(b)
print(a)

[[10.  2.]
 [ 3.  4.]]
[[1 2]
 [3 4]]


The following also works:

In [49]:
a = np.array([[1, 2], [3, 4]])
b = np.zeros(a.shape) # b = np.zeros_like(a) also works

b[:,:] = a

b[0,0] = 10
print(b)
print(a)

[[10.  2.]
 [ 3.  4.]]
[[1 2]
 [3 4]]


## Some useful tips

In [50]:
# NumPy has a random number generator:
A = np.random.randn(10,3)
print(A)

[[-0.55725741  0.6141555   0.08449304]
 [-0.87275016 -0.79582987  1.14908838]
 [-0.55529954  1.5434045   0.84846719]
 [-0.97327643 -1.41031945 -0.25807393]
 [ 0.61928548 -2.70110078  0.54559495]
 [ 0.41924879 -0.34527386 -0.30077474]
 [ 0.70236585 -0.27318602 -1.89598396]
 [-0.87900204  1.57388412  1.40457752]
 [-0.90228383  0.67499565 -0.23039242]
 [ 0.15498344  0.48501057 -0.70908686]]


We can extract a part of A:

In [51]:
# First column
A[:,0]

array([-0.55725741, -0.87275016, -0.55529954, -0.97327643,  0.61928548,
        0.41924879,  0.70236585, -0.87900204, -0.90228383,  0.15498344])

In [52]:
# Second row
A[1,:]

array([-0.87275016, -0.79582987,  1.14908838])

In [53]:
# Second and third column, rows 3-5
A[2:5 , 1:3]

array([[ 1.5434045 ,  0.84846719],
       [-1.41031945, -0.25807393],
       [-2.70110078,  0.54559495]])

In [54]:
A>0

array([[False,  True,  True],
       [False, False,  True],
       [False,  True,  True],
       [False, False, False],
       [ True, False,  True],
       [ True, False, False],
       [ True, False, False],
       [False,  True,  True],
       [False,  True, False],
       [ True,  True, False]])

Let's consider the first column of A.

In [55]:
x = A[:,0]
print(x)

[-0.55725741 -0.87275016 -0.55529954 -0.97327643  0.61928548  0.41924879
  0.70236585 -0.87900204 -0.90228383  0.15498344]


In [56]:
x>0

array([False, False, False, False,  True,  True,  True, False, False,
        True])

This gives us an array of Booleans. Such a Boolean array can be used to extract sub-array from x: 

In [57]:
x[x>0]

array([0.61928548, 0.41924879, 0.70236585, 0.15498344])

In [58]:
x[x<0]

array([-0.55725741, -0.87275016, -0.55529954, -0.97327643, -0.87900204,
       -0.90228383])

NumPy has functions that operate on ndarray in an element-by-element fashion.

In [59]:
a = np.random.randn(5)
print(a)
b = np.random.randn(5)
print(b)

[-1.25475856 -0.32186649 -1.87751824  0.47168478  1.33741917]
[-1.53325413  0.13818988  1.26775875 -0.05890904 -0.87986801]


In [60]:
np.abs(a) # absolute value

array([1.25475856, 0.32186649, 1.87751824, 0.47168478, 1.33741917])

In [61]:
np.exp(a) # exponential function

array([0.28514469, 0.72479495, 0.15296927, 1.60269211, 3.80919991])

In [62]:
np.power(a, np.array([2, 3, 4, 5, 6])) # element-by-element exponentiation

array([ 1.57441904, -0.03334474, 12.42615198,  0.02334852,  5.72275646])

In [63]:
np.maximum(a,b) # element-by-element maximum

array([-1.25475856,  0.13818988,  1.26775875,  0.47168478,  1.33741917])

In [64]:
np.minimum(a,b) # element-by-element minimum

array([-1.53325413, -0.32186649, -1.87751824, -0.05890904, -0.87986801])

In [65]:
np.greater(a,b) # element-by-element comparison >

array([ True, False, False,  True,  True])

In [66]:
np.less(a,b) # element-by-element comparison <

array([False,  True,  True, False, False])

In [67]:
np.greater(a,b) & np.less(a,b) # bitwise and

array([False, False, False, False, False])

In [68]:
np.greater(a,b) | np.less(a,b) # bitwise or

array([ True,  True,  True,  True,  True])

In [69]:
np.logical_not(np.greater(a,b)) # bitwise not

array([False,  True,  True, False, False])

For other examples, see <https://docs.scipy.org/doc/numpy/reference/ufuncs.html>.

Arrays have some methods that are useful. For details, see <https://lectures.quantecon.org/py/numpy.html> "Array Methods".

In [70]:
a

array([-1.25475856, -0.32186649, -1.87751824,  0.47168478,  1.33741917])

In [71]:
a.min()

-1.8775182417085292

In [72]:
a.max()

0.25996463622205207

In [75]:
a.sort()
a

array([-1.12441778, -1.05790257, -0.61686947, -0.38463622,  0.25996464])